### ISSUE TITLE
Wrong state on page refresh

### ISSUE THREAD

**Issue by karelhala** [project-koku/koku-ui#287] opened 2018-11-26 06:47 UTC
**Describe the bug**
Refreshing page leads to unstable state and user is unable to use the app anymore.

**Additional context**
To fix this add update https://github.com/project-koku/koku-ui/blob/master/src/index.tsx#L11 with `insightsDeployment` and add `/` at the start of this string so react-router knows where to navigate on incorrect states.

**Comment by dlabrecq** [comment] 2018-11-26 14:40
I tried `/insights/platform/cost-management`, but still encounter the problem. Are you suggesting we use `/insightsDeployment/platform/cost-management` instead?

Note: this is a duplicate of https://github.com/project-koku/koku-ui/issues/175.

**Comment by dlabrecq** [comment] 2018-11-26 14:51
It appears that only `process.env.APP_PUBLIC_PATH` is being used, not the default `/insights/platform/cost-management` path.

**Closed** 2019-01-03 18:59 UTC
Labels: bug, insights, priority - medium
