### ISSUE TITLE
Cost management sources redirects to overview

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#924] opened 2019-07-17 09:10 UTC
**Describe the bug**
Settings > Cost Management Sources button navigates us to overview instead sources.
This happens on CI/QA beta environments.

**To Reproduce**
1. Click on Cost Management Sources
2. See error

**Expected behavior**
Navigating to sources page

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser Chrome
 - Version 75

**Comment by dlabrecq** [comment] 2019-07-17 17:07
I'm not able to reproduce with my local CI/QA beta env using Jen's account.

1. Did this just start happening recently? 
2. What user are you testing with?
3. Does the CI/QA env use a spandx.config file?

**Comment by dchorvat1** [comment] 2019-07-17 18:06
This started happening today morning, I tried using Jen's, Luke's and also my account and this occurred on all of them. I could reproduce it a few moments ago against live CI/QA env, @lcouzens also ran into this today

**Comment by dlabrecq** [comment] 2019-07-17 19:12
We recently updated the versions of react and react-router-dom. It's possible that the updated version of react-router-dom is not working as expected. I'll back out that change.

**Comment by dlabrecq** [comment] 2019-07-17 22:24
I also noted that the Insights proxy updated from v3.1.7 to 3.1.8 -- possibly related?

**Comment by dlabrecq** [comment] 2019-07-17 22:24
I don't know when the CI/QA environment will pick up my latest changes to react-router-dom, but please give the Cost Management Sources link another try?

**Comment by dlabrecq** [comment] 2019-07-18 14:02
The only other change we've made is to config/spandx.config.local.js -- see https://github.com/project-koku/koku-ui/pull/914.

Created an issue with Insights https://projects.engineering.redhat.com/browse/RHIPLAT2-777

**Comment by boaz0** [comment] 2019-07-18 14:16
Yep, that might be the problem.
@dchorvat1 are you using insight-proxy in the CI/QA environment and if you do -- what spandx.config file are you using?

Thanks.

**Comment by dlabrecq** [comment] 2019-08-20 21:50
This still still appears to be an issue. However, it now happens with the CI environment and without `beta` in the path.

**Comment by dlabrecq** [comment] 2019-09-18 14:16
Closing since Insights has fixed https://projects.engineering.redhat.com/browse/RHCLOUD-2356. This has been confirmed with qa-beta and ci-beta

**Closed by dlabrecq** 2019-09-18 14:16 UTC
Labels: bug, insights
