### ISSUE TITLE
Filter input box - help text incorrect

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#232] opened 2018-10-26 18:03 UTC
When the Cloud Cost or OpenShift Charge pages are first loaded, when the user selects a different "group by" when the page reloads, the filter input box's help text is incorrectly indicating what will be filtered upon.

1. Go to Cloud Cost or OpenShift Charges pages
2. Click on the Group Cost by or Group Charge by drop down and select an option that is not the current one.
3. After the page has re-loaded, notice the help text inside the filter input box to see if matches the group by selection.

![filterhelptext](https://user-images.githubusercontent.com/31672086/47584351-1cce4700-d928-11e8-98d3-614704d166b7.png)

The filter by help text should match the object the page is being grouped by.

**Comment by dlabrecq** [comment] 2018-11-01 13:51
This is a duplicate of https://github.com/project-koku/koku-ui/issues/190

There is a PR to fix here https://github.com/project-koku/koku-ui/pull/192

**Closed by dlabrecq** 2018-11-01 13:51 UTC
Labels: bug
