### ISSUE TITLE
Filtering on sources page does not show currently in use filters

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#815] opened 2019-04-29 12:54 UTC
**Describe the bug**
Filtering on sources page does not show currently in use filters

**To Reproduce**
1. Go to 'Add Sources'
2. Add a filter by name
3. See results but no list of current filters are shown

**Expected behavior**
We should show the filters that are in use (same as the details page filtering)

**Screenshots**
![Screenshot from 2019-04-29 13-53-54](https://user-images.githubusercontent.com/18352403/56897359-40647c80-6a86-11e9-9d2e-c22c83269a99.png)
![Screenshot from 2019-04-29 13-53-35](https://user-images.githubusercontent.com/18352403/56897363-435f6d00-6a86-11e9-94f7-f154f3a2099d.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD

**Comment by dlabrecq** [comment] 2019-04-29 13:32
This is a duplicate of https://github.com/project-koku/koku-ui/issues/649

**Closed by dlabrecq** 2019-04-29 13:32 UTC
Labels: bug, priority - low
