### ISSUE TITLE
Left hand Pane navigation not changing when clicking all services/projects buttons on the overview cost/charge cards 

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#417] opened 2019-01-18 23:50 UTC
**Describe the bug**
When you click on the 'All Services' button on the AWS cost card or the 'All Projects' button on the OCP charge card it navigates you to the respective cost/charge details pages but the tree navigation does not update/reflect the page change.

**To Reproduce**
1. Add provider
2. Click on All Services/Projects button
3. See Left hand pane current location

**Expected behavior**
I would expect the left hand pane to reflect where the user had been redirected too, so either Cloud Cost or OpenShift Charge links should be highlighted in the left hand pane.

**Screenshots**
![screenshot from 2019-01-18 23-48-58](https://user-images.githubusercontent.com/18352403/51418499-ada96d00-1b7b-11e9-8c04-2bf5700a2664.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Version: 66

**Comment by dlabrecq** [comment] 2019-01-22 02:45
This is an Insights platform issue.

https://github.com/RedHatInsights/insights-chrome/issues/65

**Comment by dlabrecq** [comment] 2019-01-22 02:46
This is a duplicate of https://github.com/project-koku/koku-ui/issues/198

**Closed by dlabrecq** 2019-01-22 02:46 UTC
Labels: bug, insights, priority - low
