### ISSUE TITLE
1st of the month lack of data on overview page is very miss-leading

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#450] opened 2019-02-01 15:12 UTC
**Describe the bug**
1st of the month lack of data on overview page is very miss-leading

**To Reproduce**
1. Navigate to overview page
2. view OCP and AWS cards

**Expected behavior**
Should have a clear way to see that we have no data for the current month rather than just blank lines everywhere.

**Screenshots**
![screenshot from 2019-02-01 09-53-56](https://user-images.githubusercontent.com/18352403/52116306-bd5b9380-2608-11e9-8270-33d655d1e491.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser chrome
 - Version 66

**Additional context**
We also show no legend for the current day, currently this is based from the the processed data I believe. Wondering whether we could change this to always show a legend for the current month, say color square and 'Feb' then add the days 1-x value when we get the specific data? And/or a tool tip saying awaiting data for current month. Either way I feel we need something visually that quickly shows why the data suddenly looks dead/blank when that's not technically the case.

Technically this is an issue when you first add a provider too, its less miss-leading at that point though as its obvious that you would be waiting for the first data ingest.

@nlcwong perhaps we can come up with some ideas based from this and our discussion.

**Comment by chambridge** [comment] 2019-02-01 15:23
@lcouzens  Looks like a dup of https://github.com/project-koku/koku-ui/issues/447

Can we just keep one open 😄 ?

**Comment by lcouzens** [comment] 2019-02-01 15:37
@chambridge Gha, so I was talking specifically about the Overview and Pete's one was talking about the Details pages, but either way your right they are related. Link and close this one maybe? Long as we capture the fact we want some sort of status view for all pages then that's cool. :+1:

**Comment by dlabrecq** [comment] 2019-02-02 02:45
I'm not seeing quite what is shown in your screenshot. The only way you would see something different is if the API returned no data -- the legend would not be shown if there is no data for the chart. Perhaps not enough data was collected, yet?

It's now 9:40 PM and I'm seeing a small amount of data (look closely for the green line) and both legends are present.

CI env:
<img width="1908" alt="screen shot 2019-02-01 at 9 37 24 pm" src="https://user-images.githubusercontent.com/17481322/52158842-65557900-266a-11e9-8786-2f34e2e32dff.png">

Production env:
<img width="1908" alt="screen shot 2019-02-01 at 9 39 57 pm" src="https://user-images.githubusercontent.com/17481322/52158846-6edee100-266a-11e9-85f5-63b56338cd99.png">

**Comment by dlabrecq** [comment] 2019-02-02 02:49
Closing as a duplicate of https://github.com/project-koku/koku-ui/issues/447

**Closed by dlabrecq** 2019-02-02 02:49 UTC
Labels: bug, duplicate, priority - medium
