### ISSUE TITLE
Adding a new OCP source crashed the UI

### ISSUE THREAD

**Issue by quarckster** [project-koku/koku-ui#418] opened 2019-01-21 09:05 UTC
**To Reproduce**
1. Click on 'Add a Source'
2. Pick 'OCP' fill the fileds by random strings
3. Click 'Confrm' button
4. The UI crashed

**Comment by dlabrecq** [comment] 2019-01-22 02:54
I could not reproduce with Insights beta. I don't see any errors and the modal closes as expected. Although, it can take a couple seconds.

Exactly what happens during the "crash"? Are there errors in the console?

Note that the modal is about to be replaced with new wizard functionality.

**Comment by dlabrecq** [comment] 2019-01-22 03:04
This modal is in the process of being completely replaced by #201. There will be a modal wizard flow per Natalie's new mocks.

**Comment by lcouzens** [comment] 2019-01-23 14:57
I think this relates back to the akamai issue again, this was testing against production. I can't reproduce this now either so the platform fixes resolved the main issue but I can get 504 errors occasionally now.

**Comment by dlabrecq** [comment] 2019-01-24 18:49
Sounds like the 504 errors are related to Insights/akamai and not the onboarding modal specifically. I have also encountered timeouts occasionally on other pages. Can this be closed, then?

**Comment by dlabrecq** [comment] 2019-01-30 20:55
Closing since https://projects.engineering.redhat.com/browse/RHIPLAT2-338 is marked completed. Feel free to reopen if encountered, again.

**Closed by dlabrecq** 2019-01-30 20:55 UTC
Labels: akamai, bug, priority - low
