### ISSUE TITLE
'Cost Managmenet Sources' link takes you to 'Overview'

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#781] opened 2019-04-23 10:42 UTC
**Describe the bug**
'Cost Managmenet Sources' link takes you to 'Overview'

**To Reproduce**
1. Go to 'Settings - Cost Management Sources'
2. See page loaded

**Expected behavior**
Should be taken to Sources list

**Screenshots**
![Screenshot from 2019-04-23 11-40-57](https://user-images.githubusercontent.com/18352403/56575044-af406200-65bc-11e9-911c-00278784dacf.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against CI beta
Workaround - Click on `Add Sources` on overview

**Comment by dlabrecq** [comment] 2019-04-23 13:09
duplicate of #711

**Closed by dlabrecq** 2019-04-23 13:09 UTC
Labels: bug, priority - medium
