### ISSUE TITLE
Cost management pages sometimes display wrong localized strings

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#1102] opened 2019-11-13 13:55 UTC
**Describe the bug**
During testing I noticed that sometimes the pages don't show correct strings, after a brief discussion with @boaz0 it turned out that this could be a problem with react-i18n localizing the texts.

**To Reproduce**
  - This behavior is inconsistent and I haven't found a way to reproduce it on purpose
  - Happens on any of the Cost Management pages, see screenshot for example

**Expected behavior**
Correct strings are displayed

**Screenshots**
![Screenshot from 2019-11-13 10-04-33](https://user-images.githubusercontent.com/46324552/68769707-14c17200-0625-11ea-8a44-ba5d12dc6662.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 70

**Additional context**
Found on both CI/QA

**Comment by dlabrecq** [comment] 2019-11-13 14:52
I have seen this occasionally, but not reproducible.

**Comment by boaz0** [comment] 2019-11-13 15:51
I am going to look into it. It could be a problem with react-i18n or webpack.
Anyway, I will take a look and find what can be done.

**Comment by boaz0** [comment] 2020-03-15 18:58
ping @dchorvat1 is this still happening?

**Comment by boaz0** [comment] 2020-03-19 08:32
I am closing this because it seems to be fixed by itself.
@dchorvat1 if you think it is not fixed please re-open.

Thanks.

**Closed by boaz0** 2020-03-19 08:32 UTC
Labels: bug, priority - low, tech-debt
