### ISSUE TITLE
Refreshing OpenShift Charge or Cloud Cost page results in 'File not found'

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#429] opened 2019-01-22 11:07 UTC
**Describe the bug**
On production if you navigate to either OCP/AWS cost details then hit F5 or refresh button page results in 'File not found'

**To Reproduce**
1. Go to OpenShift Charge or Cloud Cost
2. Click on refresh
3. See error

**Expected behavior**
Pages should reload correctly

**Screenshots**
![screenshot from 2019-01-22 11-04-58](https://user-images.githubusercontent.com/18352403/51531527-985f6780-1e35-11e9-9726-b0bfe18872d4.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser Chrome
 - Version 66

**Additional context**
This is only an issue with the production environment as its related to akamai.

**Comment by dlabrecq** [comment] 2019-01-22 16:30
I'm not able to reproduce on prod using insights-qa. I'm curious if Insights pushed a fix?

**Comment by dlabrecq** [comment] 2019-01-23 17:18
See: https://projects.engineering.redhat.com/browse/RHIPLAT2-338

**Comment by lcouzens** [comment] 2019-01-23 18:02
@dlabrecq could you still not reproduce this on production? I am getting mixed results depending on the browser. Seem FF hits it on both insights/insightsbeta whereas chrome only hits it at insightsbeta. Maybe try insightsbeta if you didn't already? Either way the api call is getting a 404 so im not actually sure if its still related to the other akamai issue.

**Comment by dlabrecq** [comment] 2019-01-24 14:38
I can see the https://access.redhat.com/insights/platform/cost-management/ocp?group_by[project]=*&order_by[charge]=desc request returns a 404, but don't know what we can do about that? This seems like an Insights issue -- I cannot reproduce it locally.

**Comment by dlabrecq** [comment] 2019-01-24 18:56
Possibly related issues:
https://github.com/project-koku/koku-ui/issues/418
https://github.com/project-koku/koku-ui/issues/414

**Comment by dlabrecq** [comment] 2019-04-05 20:12
I no longer see the issue on prod. We've closed https://github.com/RedHatInsights/insights-chrome/issues/123

**Closed by dlabrecq** 2019-04-05 20:12 UTC
Labels: bug, insights, severity - P2
