### ISSUE TITLE
Selecting the cloud cost page sort by dropdown navigates to a blank page when no provider data is loaded

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku-ui#280] opened 2018-11-14 15:59 UTC
**Describe the bug**
When no provider data is loaded, clicking the cloud cost sort by drop down navigates to a blank page requiring a manual page refresh

**To Reproduce**
1. Login to Insights Cost Management
2. Confirm that no provider data is loaded for the logged in account
3. Click on "Cloud Cost" then attempt to change the dropdown for "Sort by: Cost" to "Sort by: Name"
4. Page will transition to a blank page with the Insights Chroming

**Expected behavior**
Page will transition back to the cloud cost page w/ no loaded data and update the sort order 

**Screenshots**
![hccm_sort_by_refresh](https://user-images.githubusercontent.com/2432396/48494571-2b5ba000-e7fc-11e8-9048-4a44323bb12b.gif)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox 62

**Comment by chambridge** [comment] 2018-11-14 16:00
This is a duplicate of #174

**Closed** 2018-11-16 12:47 UTC
Labels: bug
