### ISSUE TITLE
Name is not aligned with other elements in the "details" tables

### ISSUE THREAD

**Issue by quarckster** [project-koku/koku-ui#521] opened 2019-02-25 11:33 UTC
Go to "OpenShift Details" or "AWS Details".

**Screenshots**
![screenshot_20190225_122714](https://user-images.githubusercontent.com/1011257/53334429-16ad9e80-38f9-11e9-8722-53d802465b40.png)

**Desktop (please complete the following information):**
 - OS: openSUSE 15.0
 - Browser: Firefox
 - Version: 65

**Comment by boaz0** [comment] 2019-02-25 11:48
Thanks @quarckster 
I believe it is a duplicate of #517.

**Comment by quarckster** [comment] 2019-02-25 12:21
@lcouzens ^ is it a dupe?

**Comment by lcouzens** [comment] 2019-02-25 12:48
I don't think so, unless the underlined issues fixes both problems.

**Comment by dlabrecq** [comment] 2019-02-25 14:22
I think the new PF4 table is trying to center text vertically. If you look at the other columns, it is centered with the other text.

I'll try to align this with at the top. If not, will have to open a PF4 issue.

**Closed** 2019-02-25 18:38 UTC
Labels: bug, priority - low
